import { ExportHeaderOptions } from '../components/fixture/ExportHeaderDialog';

export interface Project {
  name: string;
  logo_path?: string;
  lighting_designer?: string;
  lighting_designer_email?: string;
  lighting_designer_phone?: string;
  venue?: string;
  venue_city?: string;
  venue_state?: string;
}

export interface ExportHeader {
  title: string;
  showName?: string;
  designer?: {
    name: string;
    email?: string;
    phone?: string;
  };
  venue?: {
    name: string;
    city?: string;
    state?: string;
  };
  exportDate?: string;
  logoPath?: string;
}

/**
 * Build export header from options and project data
 */
export function buildExportHeader(
  options: ExportHeaderOptions,
  project: Project
): ExportHeader {
  const header: ExportHeader = {
    title: options.customTitle || `${project.name} - Equipment List`
  };

  if (options.includeShowName) {
    header.showName = project.name;
  }

  if (options.includeDesigner && project.lighting_designer) {
    header.designer = {
      name: project.lighting_designer,
      email: project.lighting_designer_email,
      phone: project.lighting_designer_phone
    };
  }

  if (options.includeVenue && project.venue) {
    header.venue = {
      name: project.venue,
      city: project.venue_city,
      state: project.venue_state
    };
  }

  if (options.includeDate) {
    header.exportDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }

  if (options.includeLogo && project.logo_path) {
    header.logoPath = project.logo_path;
  }

  return header;
}

/**
 * Format header for CSV export (as comment lines)
 */
export function formatHeaderForCSV(header: ExportHeader): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${header.title}`);
  lines.push('#');

  // Show name
  if (header.showName) {
    lines.push(`# Production: ${header.showName}`);
  }

  // Venue
  if (header.venue) {
    const venueStr = [
      header.venue.name,
      header.venue.city,
      header.venue.state
    ].filter(Boolean).join(', ');
    lines.push(`# Venue: ${venueStr}`);
  }

  // Designer
  if (header.designer) {
    lines.push(`# Lighting Designer: ${header.designer.name}`);
    if (header.designer.email) {
      lines.push(`#   Email: ${header.designer.email}`);
    }
    if (header.designer.phone) {
      lines.push(`#   Phone: ${header.designer.phone}`);
    }
  }

  // Export date
  if (header.exportDate) {
    lines.push(`# Exported: ${header.exportDate}`);
  }

  lines.push('#');
  lines.push('# Generated by ShowStack');
  lines.push('#');
  lines.push('');

  return lines.join('\n');
}

/**
 * Format header for Eos export (as comments in Eos format)
 */
export function formatHeaderForEos(header: ExportHeader): string {
  const lines: string[] = [];

  lines.push(`! ${header.title}`);
  lines.push('!');

  if (header.showName) {
    lines.push(`! Production: ${header.showName}`);
  }

  if (header.venue) {
    const venueStr = [
      header.venue.name,
      header.venue.city,
      header.venue.state
    ].filter(Boolean).join(', ');
    lines.push(`! Venue: ${venueStr}`);
  }

  if (header.designer) {
    lines.push(`! Lighting Designer: ${header.designer.name}`);
    if (header.designer.email) {
      lines.push(`!   ${header.designer.email}`);
    }
    if (header.designer.phone) {
      lines.push(`!   ${header.designer.phone}`);
    }
  }

  if (header.exportDate) {
    lines.push(`! Exported: ${header.exportDate}`);
  }

  lines.push('!');
  lines.push('! Generated by ShowStack');
  lines.push('!');
  lines.push('');

  return lines.join('\n');
}

/**
 * Format header for GrandMA export (as XML comments)
 */
export function formatHeaderForGrandMA(header: ExportHeader): string {
  const lines: string[] = [];

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<!--');
  lines.push(`  ${header.title}`);
  lines.push('');

  if (header.showName) {
    lines.push(`  Production: ${header.showName}`);
  }

  if (header.venue) {
    const venueStr = [
      header.venue.name,
      header.venue.city,
      header.venue.state
    ].filter(Boolean).join(', ');
    lines.push(`  Venue: ${venueStr}`);
  }

  if (header.designer) {
    lines.push(`  Lighting Designer: ${header.designer.name}`);
    if (header.designer.email) {
      lines.push(`    Email: ${header.designer.email}`);
    }
    if (header.designer.phone) {
      lines.push(`    Phone: ${header.designer.phone}`);
    }
  }

  if (header.exportDate) {
    lines.push(`  Exported: ${header.exportDate}`);
  }

  lines.push('');
  lines.push('  Generated by ShowStack');
  lines.push('-->');
  lines.push('');

  return lines.join('\n');
}
